config/routes.rb
Rails.application.routes.draw do
  resources :leagues
  devise_for :users, controllers: {registrations: 'registrations'}
  root to: 'home#index'
  resources :events, only: [:show, :edit, :update]

  get :inner_sanctum, to: 'home#inner_sanctum'

  namespace :admin do
    resources :users
    resources :events, except: :show
    resources :leagues
  end
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id                       :integer          not null, primary key
#  name                     :string(255)
#  event_date               :date
#  description              :text(65535)
#  favourites               :text(65535)
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  image_file_name          :string(255)
#  image_content_type       :string(255)
#  image_file_size          :integer
#  image_updated_at         :datetime
#  host_id                  :integer
#  cover_image_file_name    :string(255)
#  cover_image_content_type :string(255)
#  cover_image_file_size    :integer
#  cover_image_updated_at   :datetime
#  address                  :string(255)
#  league_id                :integer
#

class Event < ApplicationRecord
  has_many :bounties
  has_many :event_competitors
  has_many :competitors, -> { distinct }, through: :event_competitors, source: :user
  belongs_to :host, class_name: 'User'
  belongs_to :league

  has_attached_file :image, default_url: "/missing/coming-soon.png"
  has_attached_file :cover_image, default_url: "/missing/event-cover.jpg"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_size :image, :cover_image,
                            :less_than => 5.megabytes,
                            message: "- Bro, that image is fucking huge. Try compressing it on www.kraken.io"

  accepts_nested_attributes_for :bounties, reject_if: :all_blank, allow_destroy: true


  def winner
    # TODO - refactor
    bounty = bounties.joins(:user).order(value: :desc).first
    bounty.try(:user)
  end

  def user_points(user)
    points = bounties.find_by(user_id: user.id).try(:value)
    points ||= 0
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to admin_events_path, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    if @event.update(event_params)
      redirect_to admin_events_path, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(
        :name,
        :event_date,
        :description,
        :address,
        :favourites,
        :image,
        :cover_image,
        :host_id,
        competitor_ids: [],
        bounties_attributes: [
          :id,
          :_destroy,
          :name,
          :user_id,
          :event_id,
          :value
        ]
      )
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: :show
  before_action :check_user_owns_event, only: [:edit, :update]

  def show
  end

  def edit
    @event = current_user.hosted_event
  end

  def update
    if @event.update(event_params)
      redirect_to event_path(@event), notice: 'Fuck yeah, this event is going to be awesome!'
    else
      render :edit
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def check_user_owns_event
    set_event
    if @event.host != current_user
      redirect_to inner_sanctum_path, flash: { danger: "What the hell do you think you're doing mate?" }
    end
  end

  def event_params
    params.require(:event).permit(
      :name,
      :event_date,
      :description,
      :address,
      :favourites,
      :image,
      :cover_image,
      :host_id,
    )
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_bounty_fields.html.erb
<div class="nested-fields bounty form-inline">
  <%= f.hidden_field :event_id %>

  <div class="form-group">
    <%= f.label :value, 'Points' %>
    <%= f.number_field :value, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :name, 'Description' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :user_id %>
    <%= f.collection_select :user_id, User.all, :id, :name, { prompt: '-' }, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= link_to_remove_association f, class: 'btn btn-danger' do %>
      <span class="glyphicon glyphicon-remove"></span>
    <% end %>
  </div>
</div>

app/views/admin/events/_form.html.erb
<%= form_for [:admin, event], html: { id: 'event-form' } do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :event_date %>
    <div class='input-group'>
      <% event_date = f.object.event_date ? f.object.event_date.strftime('%d-%B-%Y') : "" %>
      <%= f.text_field :event_date, value: event_date, class: 'form-control datepicker' %>
      <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :host_id %>
    <%= f.collection_select :host_id, User.all, :id, :name, { prompt: true }, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control tinymce' %>
  </div>

  <div class="form-group row">
    <%= f.label :image, class: 'col-sm-12' %>
    <% if f.object.image.present? %>
      <div class="col-sm-3">
        <%= image_tag f.object.image.url, class: 'img-responsive' %>
      </div>
    <% end %>
    <div class="col-sm-9">
      <%= f.file_field :image, class: 'form-control' %>
      <div class="help-block">Max file size 5MB</div>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :cover_image, class: 'col-sm-12' %>
    <% if f.object.cover_image.present? %>
      <div class="col-sm-3">
        <%= image_tag f.object.cover_image.url, class: 'img-responsive' %>
      </div>
    <% end %>
    <div class="col-sm-9">
      <%= f.file_field :cover_image, class: 'form-control' %>
      <div class="help-block">Recommended size 1520x250</div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :favourites %>
    <%= f.text_area :favourites, class: 'form-control tinymce' %>
  </div>

  <div class="form-group">
    <%= f.label :competitor_ids, 'Competitors' %>
    <%= f.collection_select :competitor_ids, User.all, :id, :name, {}, multiple: true, size: 10, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :bounties %>
    <%= f.fields_for :bounties do |ff| %>
      <%= render 'bounty_fields', f: ff %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add new bounty', f, :bounties, class: 'btn btn-primary' %>
    </div>
  </div>

  <div class="actions text-center">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/events/index.html.erb
<div class="container admin-wrapper">
  <div class="pull-right">
    <%= link_to 'New Event', new_admin_event_path, class: 'btn btn-primary' %>
  </div>
  <h1>Events</h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Event date</th>
        <th>Host</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.name %></td>
          <td><%= event.event_date.try(:strftime, '%d %B, %Y') %></td>
          <td><%= event.host.try(:name) %></td>
          <td><%= link_to 'Show', event_path(event) %></td>
          <td><%= link_to 'Edit', edit_admin_event_path(event) %></td>
          <td><%= link_to 'Destroy', admin_event_path(event), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/admin/events/new.html.erb
<div class="row admin-wrapper">
  <div class="col-sm-6 col-sm-offset-3">
    <h1>New Event</h1>
    <%= render 'form', event: @event %>

    <%= link_to 'Back', admin_events_path %>
  </div>
</div>

app/views/admin/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @event.event_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @event.address_id %>
</p>

<p>
  <strong>Favourites:</strong>
  <%= @event.favourites %>
</p>

<%= link_to 'Back', admin_events_path %>