config/routes.rb
Rails.application.routes.draw do
  resources :leagues
  devise_for :users, controllers: {registrations: 'registrations'}
  root to: 'home#index'
  resources :events, only: [:show, :edit, :update]

  get :inner_sanctum, to: 'home#inner_sanctum'

  namespace :admin do
    resources :users
    resources :events, except: :show
    resources :leagues
  end
end

app/views/shared/_chief_header.html.erb
<li><%= link_to 'Home', inner_sanctum_path %></li>
<li><%= link_to 'Leagues', admin_leagues_path %></li>
<li><%= link_to 'Events', admin_events_path %></li>
<li><%= link_to 'Users', admin_users_path %></li>
<li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>

app/views/shared/_flash_messages.html.erb
<div class="flash_messages">
  <% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <%= message %>
  </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer  class="footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-center margin20">
        <div class="footer-col">
        <h3 class='text-logo'>MAJOR LEAGUE</h3>
          <div>Disclaimer:</div>
          <p>
            Your chances of being embarrassed as a result of competing are dangerously high. Individuals who take part can expect to be ridiculed, taunted, or abused, and may suffer permanent loss of self-confidence. You may even wonder why the hell you are friends with us in the first place. <br>
            Major League Incorporated will not be held responsible.
          </p>
        </div>
      </div><!--footer col-->
    </div>
    <div class="row">
      <div class="col-md-12 text-center">
        <div class="footer-btm">
          <span>&copy;<%= Time.zone.now.year %> Website by <%= link_to 'Matt Cameron', 'http://mattcameron.com.au/', target: '_blank' %></span>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<!--Main nav begin-->
<div id="home"></div>
<nav class="navbar navbar-default navbar-static-top sticky">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'MAJOR LEAGUE', root_path, class: 'text-logo' %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <%= render current_user.site_admin? ? 'shared/chief_header' : 'shared/indian_header' %>
        <% else %>
          <li class="active"><a href="/#home" class="scroll-to">Home</a></li>
          <li><a href="/#about" class="scroll-to">About</a></li>
          <li><a href="/#leaderboard" class="scroll-to">Leaderboard</a></li>
          <li><a href="/#events" class="scroll-to">Events</a></li>
          <li><a href="/#competitors" class="scroll-to">Competitors</a></li>
          <li><%= link_to 'Leagues', leagues_path %></li>
          <li><%= sign_in_or_up_link %></li>
        <% end %>

      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</nav>
<!--Main nav end-->

app/views/shared/_indian_header.html.erb
<li><%= link_to 'Home', inner_sanctum_path %></li>
<li><%= link_to 'My Event', edit_event_path(current_user.hosted_event.id) if current_user.hosted_event.present? %></li>
<li><%= link_to 'My Profile', edit_user_registration_path %></li>
<li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>

app/views/shared/_skill_fields.html.erb
<div class="nested-fields">
  <div class="form-group">
    <div class="row">
      <div class="col-sm-9">
        <%= f.label :name, 'Skill' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="col-sm-3">
        <%= f.label :value %>
        <div class="input-group">
          <%= f.number_field :value, min: 0, max: 100, class: 'form-control' %>
          <div class="input-group-addon">
            %
          </div>
        </div>
      </div>
    </div>

  </div>
</div>