config/routes.rb
Rails.application.routes.draw do
  resources :leagues
  devise_for :users, controllers: {registrations: 'registrations'}
  root to: 'home#index'
  resources :events, only: [:show, :edit, :update]

  get :inner_sanctum, to: 'home#inner_sanctum'

  namespace :admin do
    resources :users
    resources :events, except: :show
    resources :leagues
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: :inner_sanctum
  before_action :set_bro_cookie, only: :inner_sanctum
  def index
    @events = Event.order(:event_date).where.not(image_file_name: nil)
    @users = User.all
    @leader = @users.order_by_points.try(:first)
    @next_event = @events.where('event_date > ?', Time.zone.now).order(event_date: :asc).first
  end

  def inner_sanctum
    @user = current_user
    @users = User.all
    @event = @user.hosted_event
  end

  def set_bro_cookie
    cookies[:bro] = {
      value: 'cookie monster',
      expires: 1.year.from_now
    }
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def user_tasks_done?(user)
    [user.name, user.image, user.bio, user.skills].all?(&:present?)
  end

  def event_tasks_done?(event)
    [event.name, event.event_date, event.image].all?(&:present?)
  end

  def all_tasks_done?(user, event)
    user_tasks_done?(user) && event_tasks_done?(event)
  end
end

app/views/home/_about.html.erb
<section id="about">
  <div class="container">
    <div class="center-title">
      <span class="center-line"></span>
      <p>About</p>
      <h3>What the hell is this?</h3>
    </div>
    <div class="row">
      <div class="col-md-12 margin-b-20">
        <div class="about-quote">
          <p class="lead text-center">
            <span class="colored-text">Friends</span>, for too long we have argued about who is the best among us. It is time to put the past behind us and discover once and for all, who should be raised up above the common peasants and bathed in the glory he truly deserves.
          </p>
        </div>
      </div>
    </div>
      <div class="divider"></div>

    <div class="row">
      <div class="col-md-5">
        <h3 class="heading">Points</h3>
        <p class="lead">
          Each event has points up for grabs. Points work like this: If there are 10 competitors taking part, the winner gets 10 points, second gets 9, etc.<br>
          If there are 12 competitors, the winner gets 12 points, second gets 11 etc etc.
        </p>
      </div>
      <div class="col-md-5 col-md-offset-2">
        <h3 class="heading">Attendance</h3>
        <p class="lead">
          If you aren't man enough to attend an event, you may not claim that you <em>"would have won"</em> under any circumstances.
        </p>
      </div>
    </div>

    <div class="row second-row">
      <div class="col-md-5">
        <h3 class="heading">Chivalry</h3>
        <p class="lead">A true alpha dog proves his merit not by kicking sand in his opponent's face, but by rubbing it in his face afterwards. Please be courteous and remember that this is really just a pissing competition.</p>
      </div>

      <div class="col-md-5 col-md-offset-2">
        <h3 class="heading">Dirty Tactics</h3>
        <p class="lead">That being said, anyone of major league status obviously has a blatent disregard for the rules anyway, and will do whatever is necessary to win. This is a dog-eat-dog world after all.</p>
      </div>
    </div>
  </div>
</section>

app/views/home/_competitors.html.erb
<section class="blog" id="competitors">
  <div class="container">
    <div class="center-title">
      <span class="center-line"></span>
      <p>Competitors</p>
      <h3>The challengers</h3>
    </div>

    <% @users.each do |person| %>
      <% next unless person.name.present? %>
      <div class="row single-competitor">
        <div class="col-sm-3">
          <%= image_tag person.image.url(:large), class: 'img-responsive center-block' %>
        </div>
        <div class="col-sm-5">
          <h3 class="heading"><%= person.name %></h3>
          <% if person.nickname.present? %>
            <strong>Nickname:</strong>
            <p><%= person.nickname %></p>
          <% end %>
          <% if person.bio.present? %>
            <%= person.bio.try(:html_safe) %>
          <% end %>
        </div>
        <div class="col-sm-4">
          <div class="skills-wrapper">
            <% person.skills.each do |skill| %>
              <h3 class="heading-progress"><%= skill.name %> <span class="pull-right"><%= "#{skill.value}%" %></span></h3>
              <div class="progress">
                <div class="progress-bar" style="width: <%= "#{skill.value}%" %>" aria-valuemax="100" aria-valuemin="0" aria-valuenow="<%= skill.value %>" role="progressbar">
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/home/_countdown.html.erb
<% if @next_event.present? %>
  <div class="coming-soon">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-sm-offset-2 text-center">
          <div class="center-title">
            <span class="center-line"></span>
            <p>Next Major League event</p>
            <h3><%= @next_event.name %></h3>
          </div>

          <div class="count-down-1" id="clock" data-date="<%= @next_event.event_date.try(:strftime, '%Y/%m/%d %H:%M') %>">
            <div class="counts">
              <span id="weeks"></span> <p>weeks</p>
            </div>
            <div class="counts">
              <span id="days"></span> <p>days</p>
            </div>
            <div class="counts">
              <span id="hours"></span> <p>hours</p>
            </div>
            <div class="counts">
              <span id="mins"></span> <p>min</p>
            </div>
            <div class="counts">
              <span id="secs"></span> <p>sec</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/home/_events.html.erb
<section id="events">
  <div class="container">
    <div class="center-title">
      <span class="center-line"></span>
      <p>Events</p>
      <h3>The proving grounds</h3>
    </div>

    <p class="lead">Events are scheduled for the first Sunday of every month.</p>
    <p class="lead">Each person must choose and organise one event. It doesn't have to cost money, but should allow the awarding of points. If any teams are required, they will be randomly chosen by lucky dip.</p>

    <div class="cube-masonry">
      <div id="events-container" class="cbp">
        <% @events.each do |event| %>
          <div class="cbp-item">
            <%= link_to event_path(event), class: 'cbp-caption' do %>
              <div class="cbp-caption-defaultWrap">
                <%= image_tag event.image.url %>
              </div>
              <div class="cbp-caption-activeWrap">
                <div class="cbp-l-caption-alignCenter">
                  <div class="cbp-l-caption-body">
                    <div class="cbp-l-caption-title">
                      <%= event.name %>
                    </div>
                    <div class="cbp-l-caption-desc">
                      Hosted by <%= event.host.try(:name) %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div><!--.cube masonry-->

  </div>
</section>

app/views/home/_leaderboard.html.erb
<div id="leaderboard">
  <div class="container">
    <div class="center-title">
      <span class="center-line"></span>
      <p>Leaderboard</p>
      <h3>If you ain't first, you're last</h3>
    </div>

    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <ul class="list-group">
          <% @users.order_by_points.each_with_index do |person, i| %>
            <% if i == 0 %>
              <div class="media list-group-item leader">
                <div class="media-left media-middle">
                  <%= image_tag person.image.url(:medium), class: 'media-object img-circle' %>
                </div>
                <div class="media-body">
                  <h4 class="media-heading">
                    <small>Current Alpha</small><br>
                    <%= person.name %>
                    <div class="pull-right">
                      <%= person.points %> points
                    </div>
                  </h4>
                </div>
              </div>
            <% else %>
              <div class="media list-group-item">
                <div class="media-left media-middle">
                  <%= image_tag person.image.url(:thumb), class: 'media-object img-circle' %>
                </div>
                <div class="media-body">
                  <h4 class="media-heading">
                    <%= person.name %>
                    <div class="pull-right">
                      <%= person.points %> points
                    </div>
                  </h4>
                </div>
              </div>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<!--Home section start-->
<section id="slider" class=" clearfix">
  <div class="fullwidthbanner">
    <%= image_tag 'boss2.jpg', class: 'img-fullwidth' %>
    <div class="main-heading">
      <h2>Do you have what it takes</h2>
      <h2>to be..</h2>
      <div class="center-title">
        <span class="center-line"></span>
      </div>
      <h1>MAJOR LEAGUE</h1>
    </div>
  </div>
</section>
<!--Home section end-->

<%= render 'about' %>
<%= render 'leaderboard' %>
<%= render 'countdown' %>
<%= render 'events' %>
<%= render 'competitors' %>

app/views/home/inner_sanctum.html.erb
<div class="container with-padding-50">
  <% unless all_tasks_done?(@user, @event) %>
    <div class="instructions well">
      <p class="lead">
        Alright you worthless sack of shit, you need to do a couple of things:
      </p>

      <% unless user_tasks_done?(@user) %>
        <section>
          <%= link_to edit_user_registration_path do %>
            <h4>Set up your profile</h4>
          <% end %>
          <ul class="dashed">
            <% unless @user.name.present? %>
              <li>Add your real name (and optionally a nickname)</li>
            <% end %>

            <% unless @user.image.present? %>
              <li>Add a picture of your filthy face</li>
            <% end %>

            <% unless @user.bio.present? %>
              <li>Give yourself a humorous description</li>
            <% end %>

            <% unless @user.skills.present? %>
              <li>Make up some legendary skills</li>
            <% end %>
          </ul>
        </section>
      <% end %>

      <% unless event_tasks_done?(@event) %>
        <section>
          <%= link_to edit_event_path(@event) do %>
            <h4>Set up your event</h4>
          <% end %>
          <p>Everyone needs to plan and organise one event. You can pick whatever you want, but if you choose something shit, we'll bash ya.</p>
          <ul class="dashed">
            <% unless @event.name.present? %>
              <li>Give your event a name</li>
            <% end %>

            <% unless @event.event_date.present? %>
              <li>Pick a month (first Sunday of the month)</li>
            <% end %>

            <% unless @event.image.present? %>
              <li>Give your event an image</li>
            <% end %>
          </ul>
        </section>
      <% end %>
    </div>
  <% end %>

  <div class="panel panel-default">
    <div class="panel-heading">
      <strong>My Points: <%= @user.points || 0 %></strong>
    </div>
    <ul class="list-group">
      <% @user.events.each do |event| %>
        <% next unless event.name.present? %>
        <li class="list-group-item">
          <strong><%= event.name %></strong>:
          <%= event.user_points(@user) %> points
        </li>
      <% end %>
    </ul>
  </div>

  <div>
    <%= render 'leaderboard' %>
  </div>
</div>