config/routes.rb
Rails.application.routes.draw do
  resources :leagues
  devise_for :users, controllers: {registrations: 'registrations'}
  root to: 'home#index'
  resources :events, only: [:show, :edit, :update]

  get :inner_sanctum, to: 'home#inner_sanctum'

  namespace :admin do
    resources :users
    resources :events, except: :show
    resources :leagues
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  nickname               :string(255)
#  email                  :string(255)      default(""), not null
#  bio                    :text(65535)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  image_file_name        :string(255)
#  image_content_type     :string(255)
#  image_file_size        :integer
#  image_updated_at       :datetime
#  active                 :boolean          default(TRUE)
#  role                   :integer          default("regular_user")
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :image,
                    default_url: "/missing/user_:style.jpg",
                    styles: {
                      thumb: "80x80#",
                      medium: '120x120#',
                      large: '250x250#'
                    }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_size :image,
                            :less_than => 5.megabytes,
                            message: "- Bro, that image is fucking huge. Try compressing it on www.kraken.io"

  has_many :skills, dependent: :destroy
  has_many :bounties, dependent: :destroy
  has_many :event_competitors
  has_many :events, -> { distinct }, through: :event_competitors
  has_one  :hosted_event, class_name: 'Event', foreign_key: 'host_id'
  has_many :league_users
  has_many :leagues, through: :league_users

  accepts_nested_attributes_for :skills, reject_if: :all_blank
  accepts_nested_attributes_for :league_users, reject_if: :all_blank

  scope :order_by_points, -> { joins(:bounties).group('users.id').order('sum(bounties.value) desc') }

  enum role: [:regular_user, :site_admin]

  after_create :create_event

  def points
    bounties.sum(:value)
  end

  private

  def create_event
    events.create(host_id: id)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_user_path(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_user_path(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      if params[:user][:password].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
      end
      params.require(:user).permit(
        :name,
        :nickname,
        :email,
        :bio,
        :password,
        :password_confirmation,
        :image,
        skills_attributes: [
          :id,
          :name,
          :value,
          :user_id
        ]
      )
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, user], html: { id: 'user-details'} do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :nickname %>
    <%= f.text_field :nickname, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :bio %>
    <%= f.text_area :bio, class: 'form-control tinymce' %>
  </div>

  <div class="form-group row">
    <%= f.label :image, class: 'col-sm-12' %>
    <% if f.object.image.present? %>
      <div class="col-sm-3">
        <%= image_tag f.object.image.url(:medium), class: 'img-responsive' %>
      </div>
    <% end %>
    <div class="col-sm-9">
      <%= f.file_field :image, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <h4><%= f.label :skills %></h4>
    <% f.object.skills.build unless f.object.skills.present? %>
    <%= f.fields_for :skills do |ff| %>
      <%= render 'shared/skill_fields', f: ff %>
    <% end %>
    <div class="links" id="add-skill">
      <%= link_to_add_association 'Add Skill', f, :skills, partial: 'shared/skill_fields', class: 'btn btn-default' %>
    </div>
  </div>

  <div class="actions text-center">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/users/_skill_fields.html.erb
<div class="nested-fields">
  <div class="form-group">
    <div class="row">
      <div class="col-sm-9">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="col-sm-3">
        <%= f.label :value %>
        <div class="input-group">
          <%= f.number_field :value, min: 0, max: 100, class: 'form-control' %>
          <div class="input-group-addon">
            %
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/admin/users/edit.html.erb
<div class="row admin-wrapper">
  <div class="col-sm-6 col-sm-offset-3">
    <h1>Editing User</h1>
    <%= render 'form', user: @user %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container admin-wrapper">
  <div class="pull-right">
    <%= link_to 'New User', new_admin_user_path, class: 'btn btn-primary' %>
  </div>
  <h1>Users</h1>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Nickname</th>
        <th>Points</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.nickname %></td>
          <td><%= user.points %></td>
          <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
          <td><%= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/users/new.html.erb
<div class="row admin-wrapper">
  <div class="col-sm-6 col-sm-offset-3">
    <h1>New User</h1>
    <%= render 'form', user: @user %>

    <%= link_to 'Back', admin_users_path %>
  </div>
</div>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Nickname:</strong>
  <%= @user.nickname %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<p>
  <strong>Skills:</strong>
  <%= @user.skills %>
</p>

<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>